.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dzcoin_qt test_dzcoin_qt
clean: FORCE
	$(MAKE) -C .. dzcoin_qt_clean test_dzcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_dzcoin_qt_check
dzcoin-qt dzcoin-qt.exe: FORCE
	 $(MAKE) -C .. dzcoin_qt
